### ISSUE TITLE
不知道为什么没人提你的项目中没有.iml导致无法编译

### ISSUE THREAD

**Issue by harrain** [iielse/SwitchButton#11]
app中缺少app.iml,switchbutton中缺少switchbutton.iml。导致项目编译无法识别这两个module。在GitHub上其他仓库也遇到过类似情况。不知道为什么把iml文件给ignore了呢

**Comment by iielse** [comment]
不会呀，我刚才试了的 git clone ，然后用 as 打开。
iml 文件会自动生成，项目可以直接运行起来。 
不存在无法识别编译的问题。
