### ISSUE TITLE
setOnStateChangedListener()逻辑有问题

### ISSUE THREAD

**Issue by csonezp** [iielse/SwitchButton#4]
Readme我也看了，知道作者为什么要设置成这样。但是个人认为，从日常习惯上来说，这里不应该这么设计。通常来说，StateChangeListener肯定是用来监听状态变化的，而现在这里，如果单独设置这个Listener，控件就会变得无法使用，还需要单独实现内部逻辑。
如果想实现延时开关，控件只要提供一个状态检测函数，一个开关函数，APP内部逻辑可以很简单就实现延时开关操作了。而为了让控件自己支持延时开关操作而将普通意义上的StateChangeListener改成现在这样，感觉有点得不偿失啊。
还是建议修改一个这个函数的逻辑，让他仅仅能监听开关状态。

**Comment by iielse** [comment]
@csonezp 我对回调相关设计进行了改变
用 `setOnClickListener` 监听即时变化
用`setOnStateChangedListener`监听延时变化 并且用`toggleSwitch`来更新结果UI

希望能够查看新的demoapk['应用于设置界面和状态存储'的内容] 最后谢谢你提出的这个问题。
