### ISSUE TITLE
一个界面设置多个按钮会冲突。

### ISSUE THREAD

**Issue by mackkill** [iielse/SwitchButton#6]
当一个界面添加多个按钮的时候会发现，前面的按钮能点击，后面的无法点击，望楼主能看下。

**Comment by MaXiangDamian** [comment]
+1
一个界面超过两个按钮时会冲突，点击功能都没有问题，就是UI显示上有问题。

**Comment by clanaid** [comment]
+1
在list上使用会有冲突影响

**Comment by iielse** [comment]
![image](https://cloud.githubusercontent.com/assets/7521943/18423699/e1b42a28-78d9-11e6-908c-366400d4dc76.png)

+1  -_-||  这周我会看看并且进行改进，15到17号提供demo的，谢谢支持。

**Comment by iielse** [comment]
@mackkill @MaXiangDamian @clanaid 你好，请查看新demo'应用于ListView中'和'应用于RecyclerView中'，非常谢谢你们。
