### ISSUE TITLE
fragment中使用会有问题

### ISSUE THREAD

**Issue by dongweiq** [iielse/SwitchButton#8]
明明切换了状态，但是没有反应，退出再进来重新获取状态就刷新了，证明触发了事件，但是界面没变化

**Comment by dongweiq** [comment]
原来是支持了延时，能不能设置一个属性把这玩意儿关掉

**Comment by iielse** [comment]
兄弟，对不起，我错了。为了表示歉意，我决定在15到17号出一个SwitchView使用的Demo。
@dongweiq 新demo apk  [基本的API] 应该可以解决你的问题
